routes/web.php
<?php

Route::get('/', function () { return redirect('/lala'); });
Route::get('lala','HomeController@home')->name('lala');
Route::get('/home', function () { return view('welcome'); });

Route::get('/pageAksesKhusus', function(){ return view('pageAksesKhusus'); });
Route::get('/MyProfile','users\ProfilController@show')->name('MyProfile');
Route::patch('/updateprof','users\ProfilController@update')->name('updateprof');

/** Auth */
Route::get('daftar', 'users\RegistrationController@create');
Route::post('add', [
    'uses'=> 'users\RegistrationController@registrationPost',
    'as' => 'add']);
 
Route::get('signin', 'LoginController@getLogin')->name('signin');
Route::post('postLogin', 'LoginController@postLogin')->name('postLogin');
Route::get('signout', function(){
    Auth::logout();
    return redirect('/home');
})->name('signout');

/****** ADMIN**/
//email
Route::get('/email', function () { return view('send_email');});
Route::post('sendEmail/{id}', 'Email@sendEmail');
Route::post('sendEmailreject/{id}', 'Email@sendEmailreject');
Route::post('emailpkp/{id}/{revisi}/{turunan}', 'Email@emailpkp');
Route::get('approveemailpkp\{id}','Email@approveemailpkp')->name('approveemailpkp');
Route::get('rejectemailpkp\{id}','Email@rejectemailpkp')->name('rejectemailpkp');
Route::get('approveemailpdf\{id}','Email@approveemailpdf')->name('approveemailpdf');
Route::get('rejectemailpdf\{id}','Email@rejectemailpdf')->name('rejectemailpdf');
Route::get('approveemailpromo\{id}','Email@approveemailpromo')->name('approveemailpromo');
Route::get('rejectemailpromo\{id}','Email@rejectemailpromo')->name('rejectemailpromo');
Route::post('emailpromo/{id}/{revisi}/{turunan}', 'Email@emailpromo');
Route::post('emailpdf/{id}/{revisi}/{turunan}', 'Email@emailpdf');
Route::get('REmail','Email@REmail')->name('REmail');
// perubahan data form

Route::get('datases','admin\ApprovalController@datases')->name('datases');
Route::post('ses','admin\ApprovalController@ses')->name('ses');
Route::get('bacapesan/{id}','pv\pkpController@bacapesan')->name('bacapesan');
Route::get('pkpklaim/{id}','pv\pkpController@klaim')->name('pkpklaim');

Route::post('edittuser/{id_project}','pv\pkpController@edituser')->name('edittuser');
Route::post('editt/{id_project}','pv\pkpController@edit')->name('editt');
Route::post('sentpkp/{id_project}/{revisi}/{turunan}','pv\pkpController@sentpkp')->name('sentpkp');

/*User Approval*/
Route::get('/userapproval', 'admin\ApprovalController@index')->name('userapproval');
Route::get('userapproval/{id}/update', [
    'uses'=>'admin\ApprovalController@update',
    'as' =>'ua.update']);
Route::get('userapproval/{id}/destroy', [
    'uses'=>'admin\ApprovalController@destroy',
    'as' =>'ua.destroy']);
    
/*User Management*/
Route::get('usermanagement','admin\UserListController@index')->name('usermanagement');
Route::get('showuser/{id}','admin\UserListController@show')->name('showuser');
Route::get('userblok/{id}','admin\UserListController@blok')->name('userblok');
Route::get('openblok/{id}','admin\UserListController@open')->name('openblok');
Route::patch('userupdate/{id}','admin\UserListController@update')->name('userupdate');

/*Data Master*/
Route::get('DataDepartement','datamaster\DepartementController@dept')->name('dept');
Route::get('DeleteDepartement/{id}','datamaster\DepartementController@deldept')->name('deldept');
Route::post('AddDepartement','datamaster\DepartementController@adddept')->name('adddept');
Route::patch('storeupdatedept/{id}','datamaster\DepartementController@saveupdateDept')->name('storeupdatedept');

Route::get('datauom','admin\ApprovalController@datauom')->name('datauom');
Route::post('uom','admin\ApprovalController@uom')->name('uom');
Route::post('ubahjenis/{id_jenis}','admin\UserListController@isijenis')->name('ubahjenis');

Route::get('DataBahanBaku','datamaster\BahanBakuController@bahan')->name('bahanbaku');
Route::get('DeleteBahanBaku/{id}','datamaster\BahanBakuController@delbahan')->name('delbahan');
Route::get('ActiveBahan/{id}', 'datamaster\BahanBakuController@active')->name('activebahan');
Route::get('NonActiveBahan/{id}','datamaster\BahanBakuController@nonactive')->name('nonactivebahan');
Route::post('AddBahanBaku','datamaster\BahanBakuController@addbahan')->name('addbahan');
Route::patch('storeupdateBahanBaku/{id}','datamaster\BahanBakuController@saveupdateBahan')->name('storeupdatebahan');

Route::get('brand', 'datamaster\BrandController@index')->name('brand.index');
Route::post('brand/store','datamaster\BrandController@store')->name('brand.store');
Route::post('brand/{id}/update', 'datamaster\BrandController@update')->name('brand.update');
Route::get('brand/{id}/destroy', 'datamaster\BrandController@destroy')->name('brand.destroy');

Route::get('exportBpom','datamaster\datapanganController@exportBpom')->name('exportBpom');
Route::get('exportAkg','datamaster\datapanganController@exportAkg')->name('exportAkg');
Route::get('exportklaim','datamaster\datapanganController@export_klaim')->name('exportklaim');
Route::get('exportarsen','datamaster\datapanganController@exportarsen')->name('exportarsen');
Route::get('export','datamaster\datapanganController@export_excel')->name('export');
Route::get('exportsku','datamaster\datapanganController@exportsku')->name('exportsku');
Route::post('editpangan/{id}','datamaster\datapanganController@editbpom')->name('editpangan');
Route::post('editakg/{id_akg}','datamaster\datapanganController@editakg')->name('editakg');
Route::post('editsku/{id}','datamaster\datapanganController@editsku')->name('editsku');
Route::post('editklaim/{id}','datamaster\datapanganController@editklaim')->name('editklaim');
Route::post('editarsen/{id}','datamaster\datapanganController@editarsen')->name('editarsen');

Route::post('tambahpangan','datamaster\datapanganController@tambahpangan')->name('tambahpangan');
Route::post('tambahakg','datamaster\datapanganController@tambahakg')->name('tambahakg');
Route::post('tambahsku','datamaster\datapanganController@tambahsku')->name('tambahsku');
Route::post('tambaharsen','datamaster\datapanganController@tambaharsen')->name('tambaharsen');

Route::get('kemasexport','datamaster\datapanganController@kemas')->name('kemasexport');
Route::get('akg','datamaster\datapanganController@akg')->name('akg');
Route::get('klaim','datamaster\datapanganController@klaim')->name('klaim');
Route::get('sku','datamaster\datapanganController@sku')->name('sku');
Route::get('arsen','datamaster\datapanganController@arsen')->name('arsen');
Route::get('datapangan','datamaster\datapanganController@index')->name('datapangan');

Route::resource('subbrand', 'datamaster\subbrandController',['except' => [ 'show','create' ]]);
Route::resource('curren', 'datamaster\CurrensController',['except' => [ 'show','create' ]]);
Route::resource('satuan', 'datamaster\SatuanController',['except' => [ 'show','create' ]]);
Route::resource('gudang', 'datamaster\GudangController',['except' => [ 'show','create' ]]);
Route::resource('maklon', 'datamaster\MaklonController',['except' => [ 'show','create' ]]);
Route::resource('produksi', 'datamaster\ProduksiController',['except' => [ 'show','create' ]]);
Route::resource('kategori', 'datamaster\KategoriController',['except' => [ 'show','create' ]]);
Route::resource('subkategori', 'datamaster\SubkategoriController',['except' => [ 'show','create' ]]);
Route::resource('kelompok', 'datamaster\KelompokController',['except' => [ 'show','create' ]]);
Route::resource('tarkon', 'datamaster\TarkonController',['except' => [ 'show','create' ]]);

/***** PV */
Route::post('notpromo','pv\pkp2Controller@notpromo')->name('notpromo');
Route::post('notpdf','pv\pkp2Controller@notpdf')->name('notpdf');
Route::post('notpkp','pv\pkp2Controller@notpkp')->name('notpkp');
Route::get('notulenpkp','pv\pkp2Controller@notulenpkp')->name('notulenpkp');
Route::post('notulenpkpp','pv\pkp2Controller@notulenpkpp')->name('notulenpkpp');
Route::get('notulenpdf','pv\pkp2Controller@notulenpdf')->name('notulenpdf');
Route::post('notulenpdff','pv\pkp2Controller@notulenpdff')->name('notulenpdff');
Route::get('indexnotulenpromo','pv\pkp2Controller@indexnotulenpromo')->name('indexnotulenpromo');
Route::post('notulenpromoo','pv\pkp2Controller@notulenpromoo')->name('notulenpromoo');

Route::get('tabulasi','pv\pkp2Controller@tabulasi')->name('tabulasi');
Route::post('check','pv\pkp2Controller@checkpkp')->name('check');
Route::post('checkpdf','pv\pkp2Controller@checkpdf')->name('checkpdf');
Route::post('checkpromo','pv\pkp2Controller@checkpromo')->name('checkpromo');
Route::get('editpkpall','pv\pkp2Controller@editpkpall')->name('editpkpall');
Route::get('hapuscheck','pv\pkp2Controller@hapuscheck')->name('hapuscheck');
Route::get('hapuscheckpdf','pv\pkp2Controller@hapuscheckpdf')->name('hapuscheckpdf');
Route::get('hapuscheckpromo','pv\pkp2Controller@hapuscheckpromo')->name('hapuscheckpromo');
Route::get('editpdfall','pv\pkp2Controller@editpdfall')->name('editpdfall');
Route::get('hapuspdf1/{id}','pv\pkp2Controller@deletepdf1')->name('hapuspdf1');

Route::get('deletepkp1/{id}','pv\pkp2Controller@deletepkp1')->name('deletepkp1');
Route::get('deletepromo1/{id}','pv\pkp2Controller@deletepromo1')->name('deletepromo1');
Route::post('update_pkp','pv\pkp2Controller@update_pkp')->name('update_pkp');
Route::post('notulen_pkp','pv\pkp2Controller@notulen_pkp')->name('notulen_pkp');
Route::post('update_pdf','pv\pkp2Controller@update_pdf')->name('update_pdf');
Route::post('update_promo','pv\pkp2Controller@update_promo')->name('update_promo');
Route::get('editpromoall','pv\pkp2Controller@editpromoall')->name('editpromoall');
Route::get('approvalformula','pv\FormulaApprovalController@listapproval')->name('approvalformula');
Route::get('detailproject/{id}','pv\FormulaApprovalController@detailproject')->name('detailproject');
Route::get('LihatFormulaPv/{id}','pv\FormulaApprovalController@lihatformulapv')->name('lihatformulapv');

resources/views/admin/approval.blade.php
@extends('admin.tempadmin')
@section('title', 'Approval')
@section('judulhalaman','User Management')
@section('content')

@if (session('status'))
<div class="row">
  <div class="col-md-12">
    <div class="alert alert-success" style="margin:20px">
      <button type="button" class="close" data-dismiss="alert">×</button>
      {{ session('status') }}
    </div>
  </div>
</div>  
@endif

<div class="x_panel">
  <div class="x_title">
    <h3><li class="fa fa-check"> Approval</li></h3>
  </div>
	<div class="card-block">
    <div class="dt-responsive table-responsive">
      <table class="Table table-striped table-bordered nowrap">
        <thead>
        	<tr style="font-weight: bold;color:white;background-color: #2a3f54;">
            <th>Nama</th>
            <th class="text-center">Username</th>
            <th class="text-center">Email</th>           
            <th class="text-center">Departement</th>            
            <th class="text-center">Level</th>            
            <th class="text-center">Status</th>           
            <th width="17%" class="text-center">Action</th>           
          </tr>
				</thead>
				<tbody>
					@foreach ($users as $user)
					@if($user->status =='sending')
					<tr>
						<td>{{ $user->name}}</td>
						<td>{{ $user->username}}</td>
						<td>{{ $user->email}}</td>
						<td class="text-center">{{ $user->departement->dept}}</td>
						<td class="text-center">{{ $user->role->namaRule}}</td>
						<td class="text-center">
						  @if ($user->status == 'sending')
						  	<span class="label label-warning">Sending</span>                        
						  @endif
						  @if ($user->status == 'active')
						    <span class="label label-success">Active</span>                        
						  @endif 
						  @if ($user->status == 'nonactive')
						    <span class="label label-danger">NonActive</span>                        
						  @endif 
						</td>
						<td class="text-center">
    					{{csrf_field()}}
    					<button class="btn-sm btn-primary fa fa-check" data-toggle="modal" data-target="#approve{{ $user->id  }}"> Approve</a></button>
							<button class="btn-sm btn-danger fa fa-trash-o" data-toggle="modal" data-target="#delete{{ $user->id  }}"> Reject</a></button>
						</td>
            <!-- modal -->
            <div class="modal" id="approve{{ $user->id  }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog " role="document">
                <div class="modal-content">
                  <div class="modal-header">                 
                    <h3 class="modal-title" id="exampleModalLabel">Send Messenge
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button></h3>
                  </div>
                  <div class="modal-body">
                    <form class="form-horizontal form-label-left" method="POST" action="{{ url('/sendEmail',$user->id) }}" novalidate>
                    <div class="form-group row">
                      <label class="control-label col-md-2 col-sm-3 col-xs-12" for="first-name">To Email</label>
                      <div class="col-md-10 col-sm-10 col-xs-12">
                        <input id="email" class="form-control " readonly value="{{ $user->email }}" type="email" name="email" required>
                      </div>
                    </div>
                    <input type="hidden" value="active" name="status" id="status">
                    <input id="nama" class="form-control " value="{{ $user->Role->namaRule }}" type="hidden" name="role" required>
                    <input id="nama" class="form-control " value="{{ $user->username }}" type="hidden" name="username" required>
                    <input id="nama" class="form-control " value="{{ $user->Departement->dept }}" type="hidden" name="dept" required>
                    <input id="nama" class="form-control " value="{{ $user->name }}" type="hidden" name="nama" required>
			            	<input type="hidden" value="Account Confirmation" class="form-control" id="judul" name="judul"/>
			            	<input type="hidden" id="pesan" name="pesan" value="Akun yang anda buat sudah kami approve, sekarang anda bisa masuk dengan akun yang telah anda buat..">
                    <div class="modal-footer">
                      <button type="submit" class="btn btn-primary"><i class="fa fa-paper-plane"></i> Send</button>
                      {{ csrf_field() }}
                    </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
            <!-- Modal Selesai -->
            <!-- modal -->
            <div class="modal" id="delete{{ $user->id  }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog " role="document">
                <div class="modal-content">
                  <div class="modal-header">                 
                    <h3 class="modal-title" id="exampleModalLabel">Send Messenge
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button></h3>
                  </div>
                  <div class="modal-body">
                    <form class="form-horizontal form-label-left" method="POST" action="{{ url('/sendEmailreject',$user->id) }}" novalidate>
                    <div class="form-group row">
                      <label class="control-label col-md-2 col-sm-3 col-xs-12" for="first-name">To Email</label>
                      <div class="col-md-10 col-sm-10 col-xs-12">
                        <input id="email" class="form-control " value="{{ $user->email }}" type="email" name="email" required>
                      </div>
                    </div>
                    <input type="hidden" value="nonactive" name="status" id="status">
                    <input id="nama" class="form-control " value="{{ $user->Role->namaRule }}" type="hidden" name="role" required>
                    <input id="nama" class="form-control " value="{{ $user->username }}" type="hidden" name="username" required>
                    <input id="nama" class="form-control " value="{{ $user->Departement->dept }}" type="hidden" name="dept" required>
                    <input id="nama" class="form-control " value="{{ $user->name }}" type="hidden" name="nama" required>
			            	<input type="hidden" value="Account Confirmation" class="form-control" id="judul" name="judul"/>
			            	<div class="form-group row">
			            	<textarea class="form-control" required id="pesan" name="pesan"></textarea>
                    </div>
                    <div class="modal-footer">
                      <button type="submit" class="btn btn-primary"><i class="fa fa-paper-plane"></i> Send</button>
                      {{ csrf_field() }}
                    </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
            <!-- Modal Selesai -->
					</tr>   
					@endif
					@endforeach
				</tbody>
			</table>
		</div>
	</div>
</div>

@endsection

resources/views/admin/ses.blade.php
@extends('admin.tempadmin')
@section('title', 'Approval')
@section('judulhalaman','Edit Data Form')
@section('content')

<div class="row">
	<div class="col-md-6 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
    		<h3><li class="fa fa-file"> Data SES</li></h3>
  		</div>
  		<div class="card-block">
    		<table class="Table table-bordered">
					<thead>
						<tr style="font-weight: bold;color:white;background-color: #2a3f54;">
							<td width="7%px">No</td>
							<td>SES</td>
						</tr>
					</thead>
					<tbody>
						@foreach($ses as $data)
						<tr>
							<td>{{$data->id}}</td>
							<td>{{$data->ses}}</td>
						</tr>
						@endforeach
					</tbody>
				</table>
  		</div>
		</div>
	</div>
	<div class="col-md-6 col-sm-12 col-xs-12">
		<div class="x_panel">
		<form class="form-horizontal form-label-left" method="POST" action="{{ route('ses') }}" novalidate>
			<div class="x_title">
    		<h3><li class="fa fa-file"> Create New SES</li></h3>
  		</div>
  		<div class="card-block">
				<div class="form-group row">
      	  <label class="control-label text-bold col-md-1 col-sm-3 col-xs-12">SES</label>
      	  <div class="col-md-11 col-sm-9 col-xs-12">
      	    <input type="text" required name="ses" id="ses" class="form-control col-md-12 col-xs-12">
      	  </div>
      	</div>
  		</div>
			<center><button type="submit" class="btn btn-primary">Submit</button></center>
      {{ csrf_field() }}
		</div>
		</form>
	</div>
</div>		

@endsection

resources/views/admin/tempadmin.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>@yield('title')</title>
    <link href="{{ asset('img/prod.png') }}" rel="icon">
    <link href="{{ asset('vendors/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('vendors/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
    <link href="{{ asset('build/css/custom.min.css') }}" rel="stylesheet">
    <link href="{{ URL::asset('lib/advanced-datatable/css/jquery.dataTables.css') }}" rel="stylesheet" />
    <link href="{{ URL::asset('css/dataTables.bootstrap4.min.css') }}">
    <link href="{{ URL::asset('css/dataTables.min.css') }}">
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col" style="min-height:1280;">
          <div class="left_col scroll-view" >
            <div class="navbar nav_title" style="border: 2;">
              <a href="{{route('lala')}}" class="site_title"><i class="fa fa-laptop"></i><img src="{{ asset('img/logo.png') }}" width="70%" alt="..."></a>
            </div>
            <div class="clearfix"></div>
            <!-- menu profile quick info -->
					  <div class="profile clearfix">
            <center>
              <a href="{{route('lala')}}"><img style="width:110px" src="{{ asset('img/pro.png') }}" alt="..." class="profile_img"></a><br>
              <span style="font-weight: bold;color:white;">Welcome, {{ Auth::user()->role->role }}</span>
                @if( auth()->check() )
                <h2 style="color:white;">{{ Auth::user()->name }}</h2>
                @endif</center>
              <div class="clearfix"></div>
            </div><br>
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-user"></i> User Management <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{{ route('MyProfile') }}">Profil</a></li>
                      <li><a href="{{ route('usermanagement') }}">List Users</a></li>
                      <li><a href="{{ route('userapproval') }}">Approval</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-folder-open"></i> PKP / PDF / PROMO <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                    <li><a><i class="fa fa-edit"></i>Input Project<span class="fa fa-chevron-down"></span></a>
                      <ul class="nav child_menu">
                        <li><a href="{{Route('formpkp')}}">Input PKP</a> </li>
                        <li><a href="{{Route('formpdf')}}">Input PDF</a> </li>
                        <li><a href="{{Route('promo')}}">Input PROMO</a> </li>
                      </ul>
                    </li>
                    <li><a><i class="fa fa-archive"></i>Draf Project<span class="fa fa-chevron-down"></span></a>
                      <ul class="nav child_menu">
                        <li><a href="{{Route('drafpkp')}}">Draf PKP</a> </li>
                        <li><a href="{{Route('drafpdf')}}">Draf PDF</a> </li>
                        <li><a href="{{Route('drafpromo')}}">Draf PROMO</a> </li>
                      </ul>
                    </li>
                    <li><a><i class="fa fa-list"></i>List Project<span class="fa fa-chevron-down"></span></a>
                      <ul class="nav child_menu">
                        <li><a href="{{Route('listpkp')}}">List PKP</a> </li>
                        <li><a href="{{Route('listpdf')}}">List PROMO</a> </li>
                        <li><a href="{{Route('listpromo')}}">List PDF</a> </li>
                      </ul>
                    </li>
                    </ul>
                  </li>
                  <li class="mt"><a href="{{ route('dept') }}"><i class="fa fa-group"></i><span>Departement</span></a></li>
								  <li><a><i class="fa fa-edit"></i> Master Data <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{{ route('datases') }}">SES</a></li>
                      <li><a href="{{ route('datauom')}}">UOM</a></li>
                      <li><a href="{{ route('datapangan') }}">BPOM Category</a></li>
                      <li><a href="{{ route('akg') }}">Data AKG</a></li>
                      <li><a href="{{ route('sku') }}">Active SKU</a></li>
                      <li><a href="{{ route('klaim') }}">Claim Regulation</a></li>
                      <li><a href="{{ route('arsen')}}">Logam Berat</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-book"></i> Master Workbook <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{{ route('bahanbaku') }}">Bahan Baku</a></li>
                      <li><a href="{{ route('brand.index') }}">Brand</a></li>
                      <li><a href="{{ route('subbrand.index') }}">Subbrand</a></li>
                      <li><a href="{{ route('curren.index') }}">Currency</a></li>
                      <li><a href="{{ route('satuan.index') }}">Satuan</a></li>
                      <li><a href="{{ route('gudang.index') }}">Gudang</a></li>
                      <li><a href="{{ route('maklon.index') }}">Maklon</a></li>
                      <li><a href="{{ route('produksi.index') }}">Produksi</a></li>
                      <li><a href="{{ route('kategori.index') }}">Kategori</a></li>
                      <li><a href="{{ route('subkategori.index') }}">Sub Kategori</a></li>
                      <li><a href="{{ route('kelompok.index') }}">Kelompok</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
            <!-- /sidebar menu -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>
              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img width="30px" height="30px" src="{{ asset('img/pro.png') }}" alt="">{{ Auth::user()->name }}
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="{{ route('MyProfile') }}"> Profile</a></li>
                    <li><a href="{{ route('signout') }}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
          @yield('content')
          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="text-right">
            Created By Asrul4238 :)
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

  
    <!-- jQuery -->
    <script src="{{ asset('vendors/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('lib/jquery/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('vendors/jquery/dist/jquery.min.js') }}"></script>
    <!-- Bootstrap -->
    <script src="{{ asset('vendors/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('vendors/fastclick/lib/fastclick.js') }}"></script>
    <script src="{{ asset('lib/dropzoneJS/dropzone.js')}}"></script>
    <script type="text/javascript" language="javascript" src="{{ asset('lib/advanced-datatable/js/jquery.dataTables.js')}}"></script>
    <script type="text/javascript" language="javascript" src="{{ asset('lib/advanced-datatable/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{ asset('vendors/nprogress/nprogress.js') }}"></script>
    <script src="{{ asset('js/datatables.min.js')}}"></script>
    <script src="{{ asset('js/select2.min.js') }}"></script>
    <script src="{{ asset('build/js/custom.min.js') }}"></script>
    <script>
      $(document).ready(function(){
      //ajax setup
      $.ajaxSetup({
        headers:{
          'X-CSRF-TOKEN' : $('meta[name="csrf-token"]').attr('content')
          }
        });
      });
    </script>
    <script src="{{ asset('vendors/validator/validator.js') }}"></script>
    @yield('s')

    <script type="text/javascript">$('.Table').DataTable({
      "language": {
        "search": "Cari :",
        "lengthMenu": "Tampilkan _MENU_ data",
        "zeroRecords": "Tidak ada data",
        "emptyTable": "Tidak ada data",
        "info": "Menampilkan data _START_  - _END_  dari _TOTAL_ data",
        "infoEmpty": "Tidak ada data",
        "paginate": {
          "first": "Awal",
          "last": "Akhir",
          "next": ">",
          "previous": "<"
        }
      }
      });
    </script>
  </body>
</html>